apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit737-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit737-app
  template:
    metadata:
      labels:
        app: sit737-app
    spec:
      containers:
      - name: sit737-container
        image: mariyatheresa/sit737-monitoring-app
        ports:
        - containerPort: 3000
