apiVersion: v1
kind: Service
metadata:
  name: sit737-service
spec:
  selector:
    app: sit737-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31234
  type: NodePort
